### ISSUE TITLE
Question about user token

### ISSUE THREAD

**Issue by srour** [alkawryk/tinderjs#16]

**Comment by renatorib** [comment]
You need to get auth token from Tinder App.

Copy & Paste this url to get auth token

`https://www.facebook.com/dialog/oauth?client_id=464891386855067&redirect_uri=https://www.facebook.com/connect/login_success.html&scope=basic_info,email,public_profile,user_about_me,user_activities,user_birthday,user_education_history,user_friends,user_interests,user_likes,user_location,user_photos,user_relationship_details&response_type=token`

Then quickly copy the redirected url before disappear

**Comment by austin1237** [comment]
Just curious if you've figured out a way to automate this process yet?

**Comment by renatorib** [comment]
I was unable to automate yet. But it should be possible.

The problem is with X-Auth-Token. It changes whenever authenticates. So if you access the app, and then externally it will change. But, if you authenticate once, it will not change!

If you enter only once and save the X-Auth-Token, you no need to authenticate each time you access.
But, this script have other problem: the token is only getted by the /auth, it don't have setter function like setAuthToken, or whatever.

If the script had a setter, you could save the token and sets it whenever it was to use, and while not authenticate again, the system will be logged.

I'll send a pull request when I have time to solve this issue.

**Comment by necsoft** [comment]
Excuse me @renatorib, I really need to automate this process, I am currently working in an experimental data visualization based on Tinder information, and I have to find a way to offer the users the possibility to connect Tinder with my app. Do you have any clues? Any information can help me.

**Comment by renatorib** [comment]
@necsoft 
Sorry for delay ;)

You can save xAuthToken, and use it hardcoded in API, not needing to authenticate whenever you want to use. I'll create a method to set it into api. 

But, you can't access through your mobile app, or xAuthToken will change!

**Comment by shaikhfk** [comment]
@renatorib please help me with tinder for windows phone No error during debug but in emulator it says facebook login failed even after going to main page.

Thanks&Regards!

**Comment by konsumer** [comment]
Here is some code that works in nodewebkit:

``` javascript
var tinder = require('tinderjs');
var url = require('url');
var request = require('request');

var client = new tinder.TinderClient();

function facebookLogin(callback){
  var loginWindow = window.open('https://www.facebook.com/dialog/oauth?client_id=464891386855067&redirect_uri=https://www.facebook.com/connect/login_success.html&scope=basic_info,email,public_profile,user_about_me,user_activities,user_birthday,user_education_history,user_friends,user_interests,user_likes,user_location,user_photos,user_relationship_details&response_type=token', 'Login facebook', false);
  var out = {};
  loginWindow.addEventListener('load', function(){
    url.parse(loginWindow.document.URL).hash.substring(1).split('&').forEach(function(p){
      var a = p.split('=');
      out[ a[0] ] = a[1];
    });

    if (out.access_token){
      loginWindow.close();
      request.get('https://graph.facebook.com/v2.3/me?access_token=' + out.access_token, function(err, message, data){
        var me = !err ? JSON.parse(data) : message;
        me.access_token = out.access_token;
        callback(err, me);
      });
    }else{
      callback(new Error('No access token'));
    }
  });
};

facebookLogin(function(err, me){
  if (err) throw err;
  client.authorize(
    me.access_token,
    me.id,
    function(){
      client.getRecommendations(10, function(error, data){
        console.log(data.results);
      });
    }
  );
});
```

**Comment by renatorib** [comment]
@konsumer great!

**Comment by necsoft** [comment]
Thanks a lot @konsumer!

**Comment by konsumer** [comment]
Hope it's useful. I think maybe the else statement should be left out, because it gets loaded multiple times if the user has never logged in. Basically the callback should only be called if there is a real error or the access_token is set.

**Comment by konsumer** [comment]
I made a [simple lil tool](https://github.com/konsumer/tindercred/releases/tag/1.0.0) for myself to get the info for hard-coding.

**Comment by sarment0** [comment]
@konsumer I tried your nwjs app, and it's not working, i don't have access to the access_token.. Can you check this?
